build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "OpenVDBNativePlugin/0.0.1"
    CONAN_USERNAME: "aminubuntu7"
    CONAN_LOGIN_USERNAME: "aminubuntu7@gmail.com"
    CONAN_CHANNEL: "development"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
    CONAN_UPLOAD: "https://amintest.jfrog.io/artifactory/api/conan/conan"

    matrix:
       # Fix me 
       # "CONAN_VISUAL_VERSIONS: 12" occurs unknown compile error
       #
       # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
       #   CONAN_VISUAL_VERSIONS: 12
       #   CONAN_BUILD_TYPES: Release

       - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
         CONAN_VISUAL_VERSIONS: 14
         CONAN_BUILD_TYPES: Release

       - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
         CONAN_VISUAL_VERSIONS: 15
         CONAN_BUILD_TYPES: Release

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan==1.9.2 --upgrade
  - pip.exe install conan_package_tools==0.20.0
  - conan user # It creates the conan data directory
  - conan remote add conan https://amintest.jfrog.io/artifactory/api/conan/conan

test_script:
  - python build.py
